import{a as L,S,i as y}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const v=L.create({baseURL:"https://pixabay.com/api/",params:{key:"13983728-c7bbdcf2d20cfa49f01a0b8c6",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function m(o,t=1){const{data:a}=await v.get("",{params:{q:o,page:t,per_page:15}});return a}function g(o){return o.map(({webformatURL:t,largeImageURL:a,tags:n,likes:e,views:s,comments:l,downloads:b})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${a}">
                <img class="gallery-image" src="${t}" alt="${n}">
                <ul class="wrapper">
                    <li>Likes<span>${e}</span></li>
                    <li>Views<span>${s}</span></li>
                    <li>Comments<span>${l}</span></li>
                    <li>Downloads<span>${b}</span></li>
                </ul>
            </a>
        </li>
    `).join("")}const w=document.querySelector(".search-form"),p=document.querySelector(".gallery-list"),r=document.querySelector(".loader"),c=document.querySelector(".js-btn-load"),h=new S(".gallery-list a",{animationSpeed:200,animationSlide:!0,disableScroll:!1,history:!1,captionsData:"alt",captionDelay:250});let i=1,f=15,d="",u=0;c.style.display="none";w.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements.search.value.trim(),i=1,p.innerHTML="",!d){y.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}r.classList.remove("hidden"),r.style.display="block",c.style.display="none";try{const t=await m(d,i);if(t.total){u=t.totalHits;const a=g(t.hits);p.innerHTML=a,h.refresh(),u>=i*f&&(c.style.display="block")}else return y.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),r.style.display="none";r.classList.add("hidden"),r.style.display="none"}catch(t){console.error("Error searching images:",t.message),r.classList.add("hidden"),r.style.display="none"}});c.addEventListener("click",async o=>{i+=1,r.classList.remove("hidden"),r.style.display="block",u<=i*f&&(c.style.display="none",y.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),r.classList.add("hidden"),r.style.display="none");try{const t=await m(d,i);if(t.hits.length===0)y.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});else{const a=g(t.hits);p.insertAdjacentHTML("beforeend",a),h.refresh();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}r.classList.add("hidden"),r.style.display="none"}catch(t){console.error("Error loading more images:",t.message),r.classList.add("hidden"),r.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
